### ISSUE TITLE
Doesn't work in Android

### ISSUE THREAD

**Issue by poppiestar** [wwdrew/react-native-numeric-textinput#1]
Android currently doesn't support Intl, which is used for number formatting.

**Comment by poppiestar** [comment]
Intl isn't the only problem, there appears to be an issue with onKeyPress on the numeric keyboard type.

https://github.com/facebook/react-native/issues/20713

**Comment by wwdrew** [comment]
Added some workarounds to allow it to work on Android. Keeping this open until these are fixed properly.

**Comment by wwdrew** [comment]
Closing this now, new version doesn't rely on keyPress event so it's no longer relevant.
